name: Rename GIFs with BLIP

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rename-gifs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install transformers accelerate Pillow opencv-python

      - name: Rename GIFs using BLIP
        run: python scripts/rename_blip.py

      - name: Commit and push renamed GIFs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add loop/*.gif
          git commit -m "Auto rename GIFs with BLIP" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}